development: &default
  host: localhost
  adapter: postgresql
  database: kubmo-site_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

staging:
  <<: *default
  datanase: kubmo-site_staging

test:
  <<: *default
  database: kubmo-site_test
